### ISSUE TITLE
HardFault when setting the system clock settings

### ISSUE THREAD

**Issue by chmanie** [stm32-rs/stm32f1xx-hal#338]
I am using a blue pill with the default settings from this repository. When testing I noticed that whenever I set the system clock to anything else than the default settings, the code panics.

Here's the simple example I came up with

```rust
#![no_main]
#![no_std]

#[macro_use(entry, exception)]
extern crate cortex_m_rt as rt;
extern crate cortex_m_semihosting as sh;
extern crate panic_semihosting;

extern crate stm32f1xx_hal as hal;

use hal::prelude::*;
use rt::ExceptionFrame;

#[entry]
fn main() -> ! {
    let dp = hal::stm32::Peripherals::take().unwrap();

    let mut flash = dp.FLASH.constrain();
    let rcc = dp.RCC.constrain();

    rcc
        .cfgr
        .sysclk(8.mhz()) // Removing this line will make it work!
        .freeze(&mut flash.acr);

    loop {}
}

#[allow(non_snake_case)]
#[exception]
fn HardFault(ef: &ExceptionFrame) -> ! {
    panic!("{:#?}", ef);
}
```

My `Cargo.toml`:

```toml
[package]
# ...

[package.metadata]
chip = "STM32F103C8"

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.13"
cortex-m-semihosting = "0.3.7"
panic-semihosting = "0.5.6"
embedded-hal = "0.2.5"

[dependencies.stm32f1xx-hal]
version = "0.7.0"
features = ["rt", "stm32f103", "medium"]

[profile.release]
codegen-units = 1
debug = true
lto = true
```

When debugging I am presented the following error:

```
Info : halted: PC: 0x08006408
panicked at 'ExceptionFrame {
    r0: 0xfffffffe,
    r1: 0x00000002,
    r2: 0x003d0900,
    r3: 0x20004ee4,
    r12: 0x00000000,
    lr: 0x08001e05,
    pc: 0x080026ee,
    xpsr: 0x41000000,
}', src/main.rs:169:5
```

Is there anything more I can try? Might this be related to #311?

Another simple way to break things in a reproducible way is to use the following lines in the blinky example instead of the clock configuration there:

```rust
    rcc
        .cfgr
        .sysclk(8.mhz()) // Removing this line will make it work!
        .freeze(&mut flash.acr);
```
